[config]

[templates.hyprland]
input_path = "~/.config/noctalia/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook = "hyprctl reload"

[templates.kitty]
input_path = "~/.config/noctalia/templates/kitty-colors.conf"
output_path = "~/.config/kitty/themes/Noctalia.conf"
post_hook = "kitty +kitten themes --reload-in=all Noctalia"
